version: '3'

services: 
  invoice:
    build:
      context: service/
    command: ./simpleinvoice
    ports:
      - 82:80

  ui:
    build:
      context: ui/
    links:
      - invoice
    ports:
      - 80:80



